import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ContextProvider } from '@/context/Web3Modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Metamask',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main>
					<ContextProvider>{children}</ContextProvider>
				</main>
			</body>
		</html>
	);
}
